namespace DeltaZulu.Pipeline.Core.Etw;

public static class FileInfoClassLookup
{
    public const string SchemaExtension = "DeltaZulu.Etw.FileInfoClass/1.0";

    private static readonly IReadOnlyDictionary<int, string> Names = new Dictionary<int, string>
    {
        [1] = "FileDirectoryInformation",
        [2] = "FileFullDirectoryInformation",
        [3] = "FileBothDirectoryInformation",
        [4] = "FileBasicInformation",
        [5] = "FileStandardInformation",
        [6] = "FileInternalInformation",
        [7] = "FileEaInformation",
        [8] = "FileAccessInformation",
        [9] = "FileNameInformation",
        [10] = "FileRenameInformation",
        [11] = "FileLinkInformation",
        [12] = "FileNamesInformation",
        [13] = "FileDispositionInformation",
        [14] = "FilePositionInformation",
        [15] = "FileFullEaInformation",
        [16] = "FileModeInformation",
        [17] = "FileAlignmentInformation",
        [18] = "FileAllInformation",
        [19] = "FileAllocationInformation",
        [20] = "FileEndOfFileInformation",
        [21] = "FileAlternateNameInformation",
        [22] = "FileStreamInformation",
        [23] = "FilePipeInformation",
        [24] = "FilePipeLocalInformation",
        [25] = "FilePipeRemoteInformation",
        [26] = "FileMailslotQueryInformation",
        [27] = "FileMailslotSetInformation",
        [28] = "FileCompressionInformation",
        [29] = "FileObjectIdInformation",
        [30] = "FileCompletionInformation",
        [31] = "FileMoveClusterInformation",
        [32] = "FileQuotaInformation",
        [33] = "FileReparsePointInformation",
        [34] = "FileNetworkOpenInformation",
        [35] = "FileAttributeTagInformation",
        [36] = "FileTrackingInformation",
        [37] = "FileIdBothDirectoryInformation",
        [38] = "FileIdFullDirectoryInformation",
        [39] = "FileValidDataLengthInformation",
        [40] = "FileShortNameInformation",
        [41] = "FileIoCompletionNotificationInformation",
        [42] = "FileIoStatusBlockRangeInformation",
        [43] = "FileIoPriorityHintInformation",
        [44] = "FileSfioReserveInformation",
        [45] = "FileSfioVolumeInformation",
        [46] = "FileHardLinkInformation",
        [47] = "FileProcessIdsUsingFileInformation",
        [48] = "FileNormalizedNameInformation",
        [49] = "FileNetworkPhysicalNameInformation",
        [50] = "FileIdGlobalTxDirectoryInformation",
        [51] = "FileIsRemoteDeviceInformation",
        [52] = "FileUnusedInformation",
        [53] = "FileNumaNodeInformation",
        [54] = "FileStandardLinkInformation",
        [55] = "FileRemoteProtocolInformation",
        [56] = "FileRenameInformationBypassAccessCheck",
        [57] = "FileLinkInformationBypassAccessCheck",
        [58] = "FileVolumeNameInformation",
        [59] = "FileIdInformation",
        [60] = "FileIdExtdDirectoryInformation",
        [61] = "FileReplaceCompletionInformation",
        [62] = "FileHardLinkFullIdInformation",
        [63] = "FileIdExtdBothDirectoryInformation",
        [64] = "FileDispositionInformationEx",
        [65] = "FileRenameInformationEx",
        [66] = "FileRenameInformationExBypassAccessCheck",
        [67] = "FileDesiredStorageClassInformation",
        [68] = "FileStatInformation",
        [69] = "FileMemoryPartitionInformation",
        [70] = "FileStatLxInformation",
        [71] = "FileCaseSensitiveInformation",
        [72] = "FileLinkInformationEx",
        [73] = "FileLinkInformationExBypassAccessCheck",
        [74] = "FileStorageReserveIdInformation",
        [75] = "FileCaseSensitiveInformationForceAccessCheck",
        [76] = "FileKnownFolderInformation",
        [77] = "FileStatBasicInformation",
        [78] = "FileId64ExtdDirectoryInformation",
        [79] = "FileId64ExtdBothDirectoryInformation",
        [80] = "FileIdAllExtdDirectoryInformation",
        [81] = "FileIdAllExtdBothDirectoryInformation",
        [82] = "FileStreamReservationInformation",
        [83] = "FileMupProviderInfo",
        [84] = "FileMaximumInformation"
    };

    public static string? GetName(int fileInfoClass) => Names.GetValueOrDefault(fileInfoClass);
}
