schemaVersion: 1
id: windows.eventlog.application-experience-program-inventory
name: Application Experience Program Inventory Event Log
version: 1.0.0
enabled: true
mandatory: true
resource:
  platform: windows
  family: eventlog
  channel: Microsoft-Windows-Application-Experience/Program-Inventory
input:
  table: EventLog
  schema: WindowsEventLog.Native
output:
  mode: FilterAndSelect
  format: ndjson
  preserveOriginalFieldNames: true
  preserveRawEvent: true
  metadataEnvelope: true
  eventEnvelope: true
  onNoMatch: drop
filter:
  language: kql
  query: |
    EventLog
    | where source =~ "Microsoft-Windows-Application-Experience/Program-Inventory"
    | project *
