id: windows.eventlog.application-msiinstaller
name: MSI Installer Application package events
mandatory: false
resource:
  platform: windows
  family: eventlog
  channel: Application
  provider: MsiInstaller
filter:
  query: |
    EventLog
    | where source =~ "Application"
    | where EventId in (1022, 1033)
