id: windows.eventlog.application-emet
name: EMET Application mitigation events
mandatory: false
resource:
  platform: windows
  family: eventlog
  channel: Application
  provider: EMET
filter:
  query: |
    EventLog
    | where source =~ "Application"
    | where EventId in (1, 2)
