id: windows.eventlog.applocker-packaged-app-deployment
name: AppLocker Packaged app Deployment Event Log
resource:
  platform: windows
  family: eventlog
  channel: Microsoft-Windows-AppLocker/Packaged app-Deployment
filter:
  query: |
    EventLog
    | where source =~ "Microsoft-Windows-AppLocker/Packaged app-Deployment"
    | where EventId in (8024, 8025)
