schemaVersion: 1
id: windows.eventlog.applocker-packaged-app-deployment
name: AppLocker Packaged app Deployment Event Log
version: 1.0.0
enabled: true
resource:
  platform: windows
  family: eventlog
  channel: Microsoft-Windows-AppLocker/Packaged app-Deployment
input:
  table: Source
  schema: WindowsEventLog.Native
output:
  mode: FilterAndSelect
  format: ndjson
  preserveOriginalFieldNames: true
  preserveRawEvent: true
  metadataEnvelope: true
  eventEnvelope: true
  onNoMatch: drop
filter:
  language: kql
  query: |
    Source
    | where EventId in (8024, 8025)
    | project TimeCreated, Channel, ProviderName, EventId, RecordId, Level, Keywords, EventData, Message, RawEvent, _metadata
