id: windows.eventlog.application-crashes
name: Application crash and WER security-relevant events
mandatory: false
resource:
  platform: windows
  family: eventlog
  channel: Application
filter:
  query: |
    EventLog
    | where source =~ "Application"
    | where EventId in (1000, 1001, 1002)
