id: windows.eventlog.kernel-pnp-configuration
name: Kernel-PnP Configuration external device events
mandatory: false
resource:
  platform: windows
  family: eventlog
  channel: Microsoft-Windows-Kernel-PnP/Configuration
  provider: Microsoft-Windows-Kernel-PnP
filter:
  query: |
    EventLog
    | where source =~ "Microsoft-Windows-Kernel-PnP/Configuration"
    | where EventId in (400, 410)
