id: windows.eventlog.smbclient-security
name: SMB Client Security Event Log
mandatory: false
resource:
  platform: windows
  family: eventlog
  channel: Microsoft-Windows-SMBClient/Security
filter:
  query: |
    EventLog
    | where source =~ "Microsoft-Windows-SMBClient/Security"
